# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments_on',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dashboard_app.Comment'),
            preserve_default=False,
        ),
    ]
