# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20171023_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comments_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='login_app.Comment'),
        ),
    ]
