# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20171023_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comments_on',
        ),
        migrations.AddField(
            model_name='comment',
            name='recipient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments_on', to='login_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_by', to='login_app.User'),
        ),
    ]
